"""add channels and channel_members tables

Revision ID: 680723a80b47
Revises: f0063e230479
Create Date: 2026-06-18 15:44:02.610252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '680723a80b47'
down_revision: Union[str, Sequence[str], None] = 'f0063e230479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE channels (
            id UUID NOT NULL,
            org_id UUID NOT NULL,
            name VARCHAR NOT NULL,
            description VARCHAR,
            is_private BOOLEAN NOT NULL DEFAULT FALSE,
            created_by UUID NOT NULL,
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id),
            FOREIGN KEY (org_id) REFERENCES organizations(id),
            FOREIGN KEY (created_by) REFERENCES users(id)
        )
    """)
    op.create_index('ix_channels_org_id', 'channels', ['org_id'])
    op.create_index('ix_channels_name', 'channels', ['name'])

    op.execute("""
        CREATE TABLE channel_members (
            channel_id UUID NOT NULL,
            user_id UUID NOT NULL,
            joined_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (channel_id, user_id),
            FOREIGN KEY (channel_id) REFERENCES channels(id),
            FOREIGN KEY (user_id) REFERENCES users(id)
        )
    """)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
