"""add org_invites table

Revision ID: f0063e230479
Revises: ee1c2eaa8683
Create Date: 2026-06-12 12:19:18.516581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f0063e230479'
down_revision: Union[str, Sequence[str], None] = 'ee1c2eaa8683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE org_invites (
            id UUID NOT NULL,
            org_id UUID NOT NULL,
            invited_by UUID NOT NULL,
            email VARCHAR NOT NULL,
            role orgrole NOT NULL DEFAULT 'MEMBER',
            token VARCHAR NOT NULL,
            expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
            is_used BOOLEAN NOT NULL DEFAULT FALSE,
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id),
            FOREIGN KEY (invited_by) REFERENCES users(id),
            FOREIGN KEY (org_id) REFERENCES organizations(id)
        )
    """)
    op.create_index('ix_org_invites_email', 'org_invites', ['email'])
    op.create_index('ix_org_invites_org_id', 'org_invites', ['org_id'])
    op.create_index('ix_org_invites_token', 'org_invites', ['token'], unique=True)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_org_invites_token'), table_name='org_invites')
    op.drop_index(op.f('ix_org_invites_org_id'), table_name='org_invites')
    op.drop_index(op.f('ix_org_invites_email'), table_name='org_invites')
    op.drop_table('org_invites')
    # ### end Alembic commands ###
